// <auto-generated />
using System;
using ApartmentAssistant.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApartmentAssistant.Data.src.ApartmentAssistant.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251015130758_EntityChanges")]
    partial class EntityChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApartmentAssistant.Core.Entities.IndicationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BathroomColdWater")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BathroomHotWater")
                        .HasColumnType("numeric");

                    b.Property<decimal>("KitchenColdWater")
                        .HasColumnType("numeric");

                    b.Property<decimal>("KitchenHotWater")
                        .HasColumnType("numeric");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("IndicationEntity");
                });

            modelBuilder.Entity("ApartmentAssistant.Core.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("IdicationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("UserEntity");
                });

            modelBuilder.Entity("ApartmentAssistant.Core.Entities.IndicationEntity", b =>
                {
                    b.HasOne("ApartmentAssistant.Core.Entities.UserEntity", "User")
                        .WithOne("IndicationEntity")
                        .HasForeignKey("ApartmentAssistant.Core.Entities.IndicationEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApartmentAssistant.Core.Entities.UserEntity", b =>
                {
                    b.Navigation("IndicationEntity")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
